# 应用服务 WEB 访问端口
server:
  port: 8080


gitlab:
  base-url: https://git.pc.com.cn
  private-token: hh8qNTCLD8-HwGyAaF6g
  webhook-secret: 123456


logging:
  level:
    cn:
      com:
        pcauto:
          service:
            serviceImpl:
              MergeRequestReviewServiceImpl=DEBUG: